#!/usr/bin/env php
<?php

if (count($_SERVER['argv']) >1) {
    echo "⚠️  Sorry. Parameters are currently not supported." . PHP_EOL;
    die;
}

$_SERVER['argv'][] = 'app'; // scan app folder
$_SERVER['argv'][] = '--colors'; // ensure colors in console output
$_SERVER['argv'][] = '--show-deprecated'; // check for deprecation

include __DIR__ . '/../../bin/parallel-lint';
