#!/usr/bin/env php
<?php

$_SERVER['argv'][] = 'app'; // scan app folder
$_SERVER['argv'][] = '--colors'; // ensure colors in console output
$_SERVER['argv'][] = '--show-deprecated'; // check for deprecation

include __DIR__ . '/../../bin/parallel-lint';
