#!/usr/bin/env php
<?php

if (count($_SERVER['argv']) > 1) {
    echo "⚠️ Sorry. Parameters are currently not supported." . PHP_EOL;
    die;
}

// Summary
$_SERVER['argv'][] =  '--report=summary';

$_SERVER['argv'][] = 'app'; // scan app folder

// Use rules defined in project root or by default what defined in bespoke standards
if (file_exists(__DIR__ . '/../../../phpcs.xml')) {
    $_SERVER['argv'][] = '--standard=phpcs.xml';
} else {
    $_SERVER['argv'][] = '--standard=' . __DIR__ . '/ruleset.xml'; // rules
}
$_SERVER['argv'][] = '--extensions=php'; // only php files
$_SERVER['argv'][] = '--encoding=utf-8';

include __DIR__ . '/../../bin/phpcs';
